export const UNLOCK_GREENCHAIN_SUCCESS = 'ACCOUNT/UNLOCK_GREENCHAIN_SUCCESS';
export const UNLOCK_GREENCHAIN_ERROR = 'ACCOUNT/UNLOCK_GREENCHAIN_ERROR';
export const UNLOCK_GREENCHAIN_SUCCESS_FALSE = 'ACCOUNT/UNLOCK_GREENCHAIN_SUCCESS_FALSE';
